#!/bin/sh
# mdice - An extremely simple twelve-sided dice based on the chromatic scale. Useful for composition, improvisation and fun practice.

dice=("C" "G" "D" "A" "E" "B" "F# / Gb" "C# / Db" "G# / Ab" "D# / Eb" "A# / Bb" "F")

if [[ $1 -gt 0 ]]
  then
		count=$1
		while [ $count -gt 0 ]
		do
			rand=$[$RANDOM % ${#dice[@]}]
			echo ${dice[$rand]}
			(( count-- ))
		done
else
	rand=$[$RANDOM % ${#dice[@]}]
	echo ${dice[$rand]}
fi
